### PR TITLE
ADD html-webpack-plugin v4 support

### PR DESCRIPTION
**Pull request by ndelangen**
fixes: https://github.com/jantimon/html-webpack-harddisk-plugin/issues/16

title said it all, this adds compatibility for the V4 beta

### CODE REVIEW

**Comment by ndelangen** [comment]
Fails on Node4, I recommend removing that from Travis

**Comment by jantimon** [comment]
Hey @ndelangen - thanks alot :)

I guess dropping node 4 is okay now that webpack 4 supports only node 6+.

I'll try to release a new major soon

**Comment by debanjanbasu** [comment]
Please fix the tests...

**Comment by jantimon** [comment]
Merged and published as `1.0.0`

Thanks a lot

**Comment by ndelangen** [comment]
> This logic is very similar to the fixes for other plugins 👍

Because of my copy-paste skills

> Please fix the tests...

AFAIK no tests are failing?
Let me know if there's something I need to do still.

**Comment by benediktvaldez** [comment]
Hey @ndelangen 

I'm wondering if the `peerDependencies` should have been updated as well in this PR? I'm getting this warning from yarn when I install `@storybook/react` right now:

```
warning "@storybook/react > @storybook/core > @ndelangen/html-webpack-harddisk-plugin@0.2.0" has incorrect peer dependency "html-webpack-plugin@^2.0.0 || ^3.0.0".
```

**Pull request merged**
